<?php

namespace ContainerIZz3idg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCatTable4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.UDO16ki.App\Entity\CatTable' shared service.
     *
     * @return \App\Entity\CatTable
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.UDO16ki": it needs an instance of "App\\Entity\\CatTable" but this type has been excluded in "config/services.yaml".');
    }
}
