<?php

namespace ContainerIZz3idg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReportesdetService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Mzw40md.App\Entity\Reportesdet' shared service.
     *
     * @return \App\Entity\Reportesdet
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Mzw40md": it needs an instance of "App\\Entity\\Reportesdet" but this type has been excluded in "config/services.yaml".');
    }
}
