<?php

namespace ContainerIZz3idg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReportesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.1K82U8P.App\Entity\Reportes' shared service.
     *
     * @return \App\Entity\Reportes
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.1K82U8P": it needs an instance of "App\\Entity\\Reportes" but this type has been excluded in "config/services.yaml".');
    }
}
