<?php

namespace ContainerIZz3idg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyncBasesTablesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.8K8lY4w.App\Entity\SyncBasesTables' shared service.
     *
     * @return \App\Entity\SyncBasesTables
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.8K8lY4w": it needs an instance of "App\\Entity\\SyncBasesTables" but this type has been excluded in "config/services.yaml".');
    }
}
