<?php

namespace ContainerIZz3idg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSysTypetypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.q5NxWoY.App\Entity\SysTypetype' shared service.
     *
     * @return \App\Entity\SysTypetype
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.q5NxWoY": it needs an instance of "App\\Entity\\SysTypetype" but this type has been excluded in "config/services.yaml".');
    }
}
