<?php

namespace ContainerIZz3idg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecRolemenuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.EqmxhZu.App\Entity\SecRolemenu' shared service.
     *
     * @return \App\Entity\SecRolemenu
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.EqmxhZu": it needs an instance of "App\\Entity\\SecRolemenu" but this type has been excluded in "config/services.yaml".');
    }
}
