<?php

namespace ContainerAilBCvo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCatEntityService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.lOoTOBt.App\Entity\CatEntity' shared service.
     *
     * @return \App\Entity\CatEntity
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.lOoTOBt": it needs an instance of "App\\Entity\\CatEntity" but this type has been excluded in "config/services.yaml".');
    }
}
