<?php

namespace ContainerAilBCvo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCatEntityRelsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.8daNUFD.App\Entity\CatEntityRels' shared service.
     *
     * @return \App\Entity\CatEntityRels
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.8daNUFD": it needs an instance of "App\\Entity\\CatEntityRels" but this type has been excluded in "config/services.yaml".');
    }
}
