<?php

namespace ContainerAilBCvo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCatBases2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.IT0XPkp.App\Entity\CatBases' shared service.
     *
     * @return \App\Entity\CatBases
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.IT0XPkp": it needs an instance of "App\\Entity\\CatBases" but this type has been excluded in "config/services.yaml".');
    }
}
