<?php

namespace ContainerAilBCvo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSysZoneTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\SysZoneType' shared autowired service.
     *
     * @return \App\Form\SysZoneType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/SysZoneType.php';

        return $container->privates['App\\Form\\SysZoneType'] = new \App\Form\SysZoneType();
    }
}
