<?php

namespace ContainerAilBCvo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyncBasesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.KU1wdbS.App\Entity\SyncBases' shared service.
     *
     * @return \App\Entity\SyncBases
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.KU1wdbS": it needs an instance of "App\\Entity\\SyncBases" but this type has been excluded in "config/services.yaml".');
    }
}
