<?php

namespace ContainerAilBCvo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecUser2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.uRl3ewN.App\Entity\SecUser' shared service.
     *
     * @return \App\Entity\SecUser
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.uRl3ewN": it needs an instance of "App\\Entity\\SecUser" but this type has been excluded in "config/services.yaml".');
    }
}
