<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUhwAAvv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUhwAAvv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUhwAAvv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUhwAAvv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUhwAAvv\App_KernelDevDebugContainer([
    'container.build_hash' => 'UhwAAvv',
    'container.build_id' => '8efd3844',
    'container.build_time' => 1702350087,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUhwAAvv');
