<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CatBases extends \App\Entity\CatBases implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'active' => [parent::class, 'active', null],
        "\0".parent::class."\0".'basedb' => [parent::class, 'basedb', null],
        "\0".parent::class."\0".'hostdb' => [parent::class, 'hostdb', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'nameconn' => [parent::class, 'nameconn', null],
        "\0".parent::class."\0".'passdb' => [parent::class, 'passdb', null],
        "\0".parent::class."\0".'portdb' => [parent::class, 'portdb', null],
        "\0".parent::class."\0".'schemas' => [parent::class, 'schemas', null],
        "\0".parent::class."\0".'userdb' => [parent::class, 'userdb', null],
        'active' => [parent::class, 'active', null],
        'basedb' => [parent::class, 'basedb', null],
        'hostdb' => [parent::class, 'hostdb', null],
        'id' => [parent::class, 'id', null],
        'nameconn' => [parent::class, 'nameconn', null],
        'passdb' => [parent::class, 'passdb', null],
        'portdb' => [parent::class, 'portdb', null],
        'schemas' => [parent::class, 'schemas', null],
        'userdb' => [parent::class, 'userdb', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
