<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SysType extends \App\Entity\SysType implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'active' => [parent::class, 'active', null],
        "\0".parent::class."\0".'codetree' => [parent::class, 'codetree', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'leveltree' => [parent::class, 'leveltree', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'nametree' => [parent::class, 'nametree', null],
        "\0".parent::class."\0".'orderlist' => [parent::class, 'orderlist', null],
        "\0".parent::class."\0".'parentId' => [parent::class, 'parentId', null],
        "\0".parent::class."\0".'property' => [parent::class, 'property', null],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null],
        'active' => [parent::class, 'active', null],
        'codetree' => [parent::class, 'codetree', null],
        'id' => [parent::class, 'id', null],
        'leveltree' => [parent::class, 'leveltree', null],
        'name' => [parent::class, 'name', null],
        'nametree' => [parent::class, 'nametree', null],
        'orderlist' => [parent::class, 'orderlist', null],
        'parentId' => [parent::class, 'parentId', null],
        'property' => [parent::class, 'property', null],
        'type' => [parent::class, 'type', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
