<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SecCompany extends \App\Entity\SecCompany implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'active' => [parent::class, 'active', null],
        "\0".parent::class."\0".'comments' => [parent::class, 'comments', null],
        "\0".parent::class."\0".'country' => [parent::class, 'country', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'createdBy' => [parent::class, 'createdBy', null],
        "\0".parent::class."\0".'cuit' => [parent::class, 'cuit', null],
        "\0".parent::class."\0".'deletedAt' => [parent::class, 'deletedAt', null],
        "\0".parent::class."\0".'deletedBy' => [parent::class, 'deletedBy', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'expiredate' => [parent::class, 'expiredate', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'ladActive' => [parent::class, 'ladActive', null],
        "\0".parent::class."\0".'ladAuth0connectionname' => [parent::class, 'ladAuth0connectionname', null],
        "\0".parent::class."\0".'ladBillingemailaddress' => [parent::class, 'ladBillingemailaddress', null],
        "\0".parent::class."\0".'ladExtradata' => [parent::class, 'ladExtradata', null],
        "\0".parent::class."\0".'ladName' => [parent::class, 'ladName', null],
        "\0".parent::class."\0".'ladOid' => [parent::class, 'ladOid', null],
        "\0".parent::class."\0".'logo' => [parent::class, 'logo', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'shortdescription' => [parent::class, 'shortdescription', null],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        "\0".parent::class."\0".'updatedBy' => [parent::class, 'updatedBy', null],
        'active' => [parent::class, 'active', null],
        'comments' => [parent::class, 'comments', null],
        'country' => [parent::class, 'country', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'createdBy' => [parent::class, 'createdBy', null],
        'cuit' => [parent::class, 'cuit', null],
        'deletedAt' => [parent::class, 'deletedAt', null],
        'deletedBy' => [parent::class, 'deletedBy', null],
        'description' => [parent::class, 'description', null],
        'expiredate' => [parent::class, 'expiredate', null],
        'id' => [parent::class, 'id', null],
        'ladActive' => [parent::class, 'ladActive', null],
        'ladAuth0connectionname' => [parent::class, 'ladAuth0connectionname', null],
        'ladBillingemailaddress' => [parent::class, 'ladBillingemailaddress', null],
        'ladExtradata' => [parent::class, 'ladExtradata', null],
        'ladName' => [parent::class, 'ladName', null],
        'ladOid' => [parent::class, 'ladOid', null],
        'logo' => [parent::class, 'logo', null],
        'name' => [parent::class, 'name', null],
        'shortdescription' => [parent::class, 'shortdescription', null],
        'telephone' => [parent::class, 'telephone', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
        'updatedBy' => [parent::class, 'updatedBy', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
