<?php

namespace ContainerUhwAAvv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1K82U8PService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1K82U8P' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1K82U8P'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'reporteEntity' => ['privates', '.errored..service_locator.1K82U8P.App\\Entity\\Reportes', NULL, 'Cannot autowire service ".service_locator.1K82U8P": it needs an instance of "App\\Entity\\Reportes" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'reporteEntity' => 'App\\Entity\\Reportes',
        ]);
    }
}
