<?php

namespace ContainerUhwAAvv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IT0XPkpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IT0XPkp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IT0XPkp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'base' => ['privates', '.errored..service_locator.IT0XPkp.App\\Entity\\CatBases', NULL, 'Cannot autowire service ".service_locator.IT0XPkp": it needs an instance of "App\\Entity\\CatBases" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'base' => 'App\\Entity\\CatBases',
            'entityManager' => '?',
        ]);
    }
}
