<?php

namespace ContainerUhwAAvv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecMenuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.0oK2u4J.App\Entity\SecMenu' shared service.
     *
     * @return \App\Entity\SecMenu
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.0oK2u4J": it needs an instance of "App\\Entity\\SecMenu" but this type has been excluded in "config/services.yaml".');
    }
}
