<?php

namespace ContainerUhwAAvv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecCompanyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.C1kPkii.App\Entity\SecCompany' shared service.
     *
     * @return \App\Entity\SecCompany
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.C1kPkii": it needs an instance of "App\\Entity\\SecCompany" but this type has been excluded in "config/services.yaml".');
    }
}
