<?php

namespace ContainerUhwAAvv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecRoleTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\SecRoleType' shared autowired service.
     *
     * @return \App\Form\SecRoleType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/SecRoleType.php';

        return $container->privates['App\\Form\\SecRoleType'] = new \App\Form\SecRoleType();
    }
}
