<?php

namespace ContainerUhwAAvv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSysZoneService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.sMLbUQ..App\Entity\SysZone' shared service.
     *
     * @return \App\Entity\SysZone
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.sMLbUQ.": it needs an instance of "App\\Entity\\SysZone" but this type has been excluded in "config/services.yaml".');
    }
}
