<?php

namespace ContainerUhwAAvv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecRoleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.EDHHIo_.App\Entity\SecRole' shared service.
     *
     * @return \App\Entity\SecRole
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.EDHHIo_": it needs an instance of "App\\Entity\\SecRole" but this type has been excluded in "config/services.yaml".');
    }
}
