<?php

namespace ContainerUhwAAvv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecAuditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.FtujEZm.App\Entity\SecAudit' shared service.
     *
     * @return \App\Entity\SecAudit
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.FtujEZm": it needs an instance of "App\\Entity\\SecAudit" but this type has been excluded in "config/services.yaml".');
    }
}
