<?php

namespace ContainerLLu5WKm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MJVJ34aService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mJVJ34a' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mJVJ34a'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'syncbase' => ['privates', '.errored..service_locator.mJVJ34a.App\\Entity\\SyncBases', NULL, 'Cannot autowire service ".service_locator.mJVJ34a": it needs an instance of "App\\Entity\\SyncBases" but this type has been excluded in "config/services.yaml".'],
        ], [
            'doctrine' => '?',
            'syncbase' => 'App\\Entity\\SyncBases',
        ]);
    }
}
