<?php

namespace ContainerLLu5WKm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_URl3ewNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uRl3ewN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uRl3ewN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'passwordEncoder' => ['privates', '.errored.7c9.lTt', NULL, 'Cannot determine controller argument for "App\\Controller\\UserController::chopass()": the $passwordEncoder argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Security\\Core\\Encoder\\UserPasswordEncoderInterface".'],
            'user' => ['privates', '.errored..service_locator.uRl3ewN.App\\Entity\\SecUser', NULL, 'Cannot autowire service ".service_locator.uRl3ewN": it needs an instance of "App\\Entity\\SecUser" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'passwordEncoder' => '?',
            'user' => 'App\\Entity\\SecUser',
        ]);
    }
}
