<?php

namespace ContainerLLu5WKm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCatRelsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.gSBHE_A.App\Entity\CatRels' shared service.
     *
     * @return \App\Entity\CatRels
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.gSBHE_A": it needs an instance of "App\\Entity\\CatRels" but this type has been excluded in "config/services.yaml".');
    }
}
