<?php

namespace ContainerLLu5WKm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCatFieldsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._A8A.3V.App\Entity\CatFields' shared service.
     *
     * @return \App\Entity\CatFields
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator._A8A.3V": it needs an instance of "App\\Entity\\CatFields" but this type has been excluded in "config/services.yaml".');
    }
}
