<?php

namespace ContainerLLu5WKm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCatBasesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6jjJ21g.App\Entity\CatBases' shared service.
     *
     * @return \App\Entity\CatBases
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.6jjJ21g": it needs an instance of "App\\Entity\\CatBases" but this type has been excluded in "config/services.yaml".');
    }
}
