<?php

namespace ContainerLLu5WKm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSysTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.c0to4HK.App\Entity\SysType' shared service.
     *
     * @return \App\Entity\SysType
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.c0to4HK": it needs an instance of "App\\Entity\\SysType" but this type has been excluded in "config/services.yaml".');
    }
}
